# Generated by Django 5.0.4 on 2024-04-07 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visiteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.IntegerField(blank=True, null=True)),
                ("adresse", models.TextField(blank=True)),
                ("date_visite", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Visiteur",
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse_ligne1", models.CharField(max_length=255)),
                (
                    "adresse_ligne2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ville", models.CharField(max_length=100)),
                ("code_postal", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "Adresse-Consommateur",
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("id_catg", models.AutoField(primary_key=True, serialize=False)),
                ("libelle_catg", models.CharField(default="", max_length=30)),
            ],
            options={
                "db_table": "Categorie",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("id_com", models.AutoField(primary_key=True, serialize=False)),
                ("date_comm", models.DateTimeField(auto_now_add=True)),
                (
                    "statut_commd",
                    models.CharField(
                        choices=[
                            ("en_attente", "En Attente"),
                            ("validee", "Validée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "Commande",
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("id_fourn", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("adresse_fourn", models.CharField(max_length=255)),
                ("telephone", models.IntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "Fournissuer",
            },
        ),
        migrations.CreateModel(
            name="Consommateur",
            fields=[
                (
                    "visiteur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ApplicationVente.visiteur",
                    ),
                ),
                ("mot_passe", models.CharField(max_length=16)),
                (
                    "type_consommateur",
                    models.CharField(
                        choices=[
                            ("allergiques ", "Allergiques "),
                            ("asthmatique", "Asmatique"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "adresse_consommateur",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommateur",
                        to="ApplicationVente.adresse",
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Consommateur",
            },
            bases=("ApplicationVente.visiteur",),
        ),
        migrations.CreateModel(
            name="DetailCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ApplicationVente.commande",
                    ),
                ),
            ],
            options={
                "db_table": "DetailCommande",
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                ("id_fact", models.AutoField(primary_key=True, serialize=False)),
                ("date_facture", models.DateField()),
                ("remise", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "Detail_Commande",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Paiement",
                        to="ApplicationVente.detailcommande",
                    ),
                ),
            ],
            options={
                "db_table": "Facture",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id_prod", models.AutoField(primary_key=True, serialize=False)),
                ("nom_prod", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite_stock", models.IntegerField()),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ApplicationVente.categorie",
                    ),
                ),
                (
                    "consult_prod",
                    models.ManyToManyField(to="ApplicationVente.visiteur"),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="ApplicationVente.fournisseur",
                    ),
                ),
            ],
            options={
                "db_table": "Produit",
            },
        ),
        migrations.CreateModel(
            name="Offre",
            fields=[
                ("id_offr", models.AutoField(primary_key=True, serialize=False)),
                ("date_debut_offre", models.DateField()),
                ("date_fin_offre", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("offre_prod", models.ManyToManyField(to="ApplicationVente.produit")),
            ],
            options={
                "db_table": "Offre",
            },
        ),
        migrations.AddField(
            model_name="detailcommande",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ApplicationVente.produit",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApplicationVente.produit",
            ),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "visiteur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ApplicationVente.visiteur",
                    ),
                ),
                ("mot_passe", models.CharField(max_length=16)),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Administrateur",
            },
            bases=("ApplicationVente.visiteur",),
        ),
        migrations.AddField(
            model_name="produit",
            name="comm_prod",
            field=models.ManyToManyField(
                related_name="commandes_produit",
                through="ApplicationVente.Commande",
                to="ApplicationVente.consommateur",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="consommateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApplicationVente.consommateur",
            ),
        ),
    ]
